PPI :
  countries : ["AT", "BE", "BG", "CY", "CZ", "DE", "DK", "EE", "EL", "ES", "FI",
  "FR", "HR", "HU", "IE", "IT", "LT", "LU", "LV", "MT", "NL", "PL", "PT", "RO",
  "SI", "SK"]

PVI :
  countries : ["AT", "BE", "BG", "CY", "CZ", "DE", "DK", "EE", "EL", "ES", "FI",
  "FR", "HR", "HU", "IT", "LT", "LV", "MT", "PL", "PT", "RO", "SE", "SI", "SK"]

TOURISM :
  countries : ["AT", "BE", "CY", "CZ", "DE", "DK", "EL", "ES", "FI", "FR", "HR",
  "HU", "IT", "LT", "LU", "LV", "MT", "NL", "PL", "PT", "RO", "SE", "SI", "SK"]
