on:
  workflow_dispatch:
  push:
    branches: "62-create-website"
    
name: Publish website

jobs:
  publish-website:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.2'

      - name: Reconfigure Java support 
        run: sudo R CMD javareconf

      - name: Install libcurl4
        run:  sudo apt install libcurl4-openssl-dev
        
      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
          
      - name: Install Minio Client
        run: |
          wget -q https://dl.min.io/client/mc/release/linux-amd64/mc -O /usr/local/bin/mc
          chmod +x /usr/local/bin/mc
          export MC_HOST_s3=https://${{ secrets.AWS_ACCESS_KEY_ID }}:${{ secrets.AWS_SECRET_ACCESS_KEY }}@${{ secrets.AWS_S3_ENDPOINT }}
       
      - name: Retrieve stores from s3
        run: mc ls s3

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: website/
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_CI }}
