on:
  workflow_dispatch:
  schedule:
    - cron: '33 16 25-31 * *'
    - cron: '50 20 13 * *'

name: Run Pipeline

jobs:
  run-pipeline:
    runs-on: ubuntu:22.04
    container:
      image: thomasfaria/esa-nowcasting-2023:v4.0.1
    permissions:
      contents: write
    steps:

      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Install python from mamba
        run: |
          wget -q https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh -O mambaforge.sh
          # Install mambaforge latest version
          /bin/bash mambaforge.sh -b -p /opt/mamba
          # Set specified Python version in base Conda env
          mamba install python==3.10.4
          # Install essential Python packages
          mamba env update -n base -f conda-env.yml
          # Activate custom Conda env by default in shell
#          echo ". /opt/mamba/etc/profile.d/conda.sh && conda activate" >> ${HOME}/.bashrc
          # fix for version GLIBCXX_3.4.30
          sudo rm /usr/lib/x86_64-linux-gnu/libstdc++.so.6
          sudo ln -s /opt/mamba/lib/libstdc++.so.6 /usr/lib/x86_64-linux-gnu/libstdc++.so.6
          # Fix permissions
#          chown -R ${USERNAME}:${GROUPNAME} ${HOME} /opt/mamba
          # Clean
          rm mambaforge.sh conda-env.yml
          mamba clean --all -f -y
    
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.1'

      - name: Install libcurl4
        run:  sudo apt install libcurl4-openssl-dev
        
      - name: Reconfigure Java support 
        run: sudo R CMD javareconf
          
      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Run Pipeline
        run: |
          source("run_all.R")
        shell: Rscript {0} 
