on:
  workflow_dispatch:
  schedule:
    - cron: '33 16 25-31 * *'
    - cron: '50 20 13 * *'

name: Run Pipeline

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.1'

      - name: Install libcurl4
        run:  sudo apt install libcurl4-openssl-dev
        
      - name: Reconfigure Java support 
        run: sudo R CMD javareconf
          
      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Run Pipeline
        run: |
          source("run_all.R")
        shell: Rscript {0} 
