name: Run Pipeline

on:
  schedule:
    # every first day of the month at 11am
    - cron: '00 11 1 * *' 
    # every 16th day of the month at 11am
    - cron: '00 11 16 * *'
    # every last week of the month at 1pm
    - cron: '00 13 25-31 * *'
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout out repository
        uses: actions/checkout@v3
        with:
          ref: 53-add-store-targets-to-s3-from-github-actions
          token: ${{ secrets.TOKEN_CI }}

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
        
      - name: Install python Dependencies
        run: pip install -r requirements.txt
    
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.2'

      - name: Reconfigure Java support 
        run: sudo R CMD javareconf

      - name: Install libcurl4
        run:  sudo apt install libcurl4-openssl-dev
        
      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Run Pipeline
        run: Rscript run_all.R
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}

      - name: Save pipeline data in s3
        run: |
          targets::tar_source(files = "R")
          targets <- yaml::read_yaml("_targets.yaml")
          lapply(targets, function(x){
            store <- x$store
            put_dir_s3(local_dir = paste0(x$store, "/"),
                       s3_dir = paste0("targets-data/", x$store, "/"),
                       bucket = "projet-esa-nowcasting")
          })
        shell: Rscript {0} 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
